# Generated by Django 4.0.3 on 2022-04-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='n_role',
            new_name='role',
        ),
    ]
